server:
  contextPath: /mcafe

jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh

      
spring:
  datasource:
    url : jdbc:mysql://localhost:3306/mcafe?useSSL=false
    username : root
    password : root
  jpa:
    hibernate:
      ddl-auto : none
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL5Dialect

spring.jpa.show-sql : true	  